services:
  core:
    image: davidsdevel/lettercms-core:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL
      - JWT_SECRET
      - LETTERCMS_URL
      - UPLOAD_URL
      
      #Credentials to enable file searching
      - UNSPLASH_API_KEY
      - UNSPLASH_SECRET_KEY
      
      #Credentials to enable file manager
      - AWS_ENDPOINT
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_BUCKET
      - AWS_REGION

      #Credentials to enable email service
      - SMTP_MAIL
      - SMTP_PASSWORD
      - SMTP_HOST
      - SMTP_PORT
