version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - setup_remote_docker:
          docker_layer_caching: true
      - run: yarn lint
      - run: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run: docker build -t $DOCKER_USER/lettercms-core:latest .
      - run: docker push $DOCKER_USER/lettercms-core:latest
      - run: ssh $SSH_USER@$SSH_HOST "cd lettercms && docker compose pull core && docker compose up -d"

workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main