version: 2.1

orbs:
  node: circleci/node@7.0.0

jobs:
  deploy-ec2:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - setup_remote_docker:
          docker_layer_caching: true
      - run: yarn lint
      - run: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run: docker build -t $DOCKER_USER/lettercms-core:latest .
      - run: docker push $DOCKER_USER/lettercms-core:latest
      - run: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run: ssh $SSH_USER@$SSH_HOST "cd lettercms && sudo docker compose pull core && sudo docker compose up -d"

workflows:
  deploy:
    jobs:
      - deploy-ec2:
          filters:
            branches:
              only: production
